import type { Config } from "tailwindcss";

// Tailwind CSS 3.4.x (CSS v4 deliberately not used: project requirement).
// Colours mirror src/game/engine/palette.ts.
export default {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "#03130a",
        deep: "#062a14",
        forest: "#005d1f",
        heading: "#13670b",
        leaf: "#277816",
        bright: "#12a415",
        star: { DEFAULT: "#e3000f", dark: "#8f1009" },
        silver: "#c9cfcb",
        cream: "#f3f6f1",
        gold: "#ffc94a",
        heat: "#ff7a1a",
        ice: "#9fe3ff",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "var(--font-sans)", "system-ui", "sans-serif"],
      },
      keyframes: {
        "beam-sway": { "0%,100%": { transform: "rotate(-6deg)" }, "50%": { transform: "rotate(6deg)" } },
        // Sways instead of spinning fully: the face stays visible, the extruded edge shows depth.
        "star-spin": { "0%,100%": { transform: "rotateY(-16deg) rotateZ(-2deg)" }, "50%": { transform: "rotateY(16deg) rotateZ(2deg)" } },
        float: { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-24px)" } },
        // Double "heartbeat" then rest: draws the eye without the washed-out opacity dip.
        "cta-beat": { "0%,40%,100%": { transform: "scale(1)" }, "10%": { transform: "scale(1.07)" }, "20%": { transform: "scale(0.99)" }, "30%": { transform: "scale(1.04)" } },
        "cta-ring": { "0%": { opacity: "0.7", transform: "scale(1)" }, "100%": { opacity: "0", transform: "scale(1.14, 1.6)" } },
        "rise-in": { "0%": { opacity: "0", transform: "translateY(60px) scale(0.96)" }, "100%": { opacity: "1", transform: "none" } },
        "pop-in": { "0%": { opacity: "0", transform: "scale(0.4)" }, "60%": { opacity: "1", transform: "scale(1.08)" }, "100%": { transform: "scale(1)" } },
        count: { "0%": { opacity: "0", transform: "scale(2.2)" }, "25%": { opacity: "1", transform: "scale(1)" }, "80%": { opacity: "1" }, "100%": { opacity: "0", transform: "scale(0.7)" } },
        drift: { "0%": { transform: "translateY(0) rotate(0deg)" }, "100%": { transform: "translateY(2200px) rotate(360deg)" } },
        shine: { "0%": { transform: "translateX(-120%) skewX(-20deg)" }, "100%": { transform: "translateX(220%) skewX(-20deg)" } },
        "spin-slow": { "0%": { transform: "translate(-50%,-50%) rotate(0deg)" }, "100%": { transform: "translate(-50%,-50%) rotate(360deg)" } },
        // Motion system: every screen enters the same way; game entry uses the star iris.
        "screen-in": { "0%": { opacity: "0", transform: "scale(1.04)" }, "100%": { opacity: "1", transform: "none" } },
        "iris-in": { "0%": { transform: "translate(-50%,-50%) scale(0) rotate(-40deg)" }, "100%": { transform: "translate(-50%,-50%) scale(1) rotate(0deg)" } },
        "fade-out": { "0%": { opacity: "1" }, "100%": { opacity: "0" } },
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "count-in": { "0%": { opacity: "0", transform: "scale(2.4)" }, "22%": { opacity: "1", transform: "scale(0.94)" }, "34%": { transform: "scale(1)" }, "82%": { opacity: "1", transform: "scale(1)" }, "100%": { opacity: "0", transform: "scale(0.8)" } },
        "go-in": { "0%": { opacity: "0", transform: "scale(0.3) rotate(-8deg)" }, "40%": { opacity: "1", transform: "scale(1.12) rotate(2deg)" }, "60%": { transform: "scale(1) rotate(0deg)" }, "100%": { opacity: "0", transform: "scale(1.5)" } },
        burst: { "0%": { opacity: "0.9", transform: "translate(-50%,-50%) scale(0.2)" }, "100%": { opacity: "0", transform: "translate(-50%,-50%) scale(1.6)" } },
        "slide-up": { "0%": { opacity: "0", transform: "translateY(40px)" }, "100%": { opacity: "1", transform: "none" } },
        "modal-in": { "0%": { opacity: "0", transform: "translateY(30px) scale(0.94)" }, "100%": { opacity: "1", transform: "none" } },
        "stamp": { "0%": { opacity: "0", transform: "scale(1.6)" }, "55%": { opacity: "1", transform: "scale(0.96)" }, "100%": { transform: "scale(1)" } },
        "prize-in": { "0%": { opacity: "0", transform: "perspective(1400px) rotateX(70deg) translateY(120px) scale(0.85)" }, "60%": { opacity: "1", transform: "perspective(1400px) rotateX(-6deg) translateY(-8px) scale(1.02)" }, "100%": { transform: "none" } },
        "foil": { "0%": { transform: "translateX(-140%) skewX(-18deg)" }, "60%,100%": { transform: "translateX(260%) skewX(-18deg)" } },
        "fall-loop": { "0%": { transform: "translateY(-80px) rotate(0deg)", opacity: "0" }, "12%": { opacity: "1" }, "85%": { opacity: "1" }, "100%": { transform: "translateY(420px) rotate(160deg)", opacity: "0" } },
        "promo": { "0%": { opacity: "0", transform: "translateY(18px)" }, "12%,88%": { opacity: "1", transform: "none" }, "100%": { opacity: "0", transform: "translateY(-18px)" } },
        "hold-ring": { "0%": { strokeDashoffset: "283" }, "100%": { strokeDashoffset: "0" } },
      },
      animation: {
        "beam-sway": "beam-sway 9s ease-in-out infinite",
        "star-spin": "star-spin 6s ease-in-out infinite",
        float: "float 5s ease-in-out infinite",
        "cta-beat": "cta-beat 1.6s ease-in-out infinite",
        "cta-ring": "cta-ring 1.6s cubic-bezier(0.16,1,0.3,1) infinite",
        "rise-in": "rise-in 0.55s cubic-bezier(0.16,1,0.3,1) both",
        "pop-in": "pop-in 0.6s cubic-bezier(0.16,1,0.3,1) both",
        count: "count 0.8s cubic-bezier(0.16,1,0.3,1) both",
        drift: "drift linear infinite",
        shine: "shine 2.2s ease-in-out infinite",
        "spin-slow": "spin-slow 60s linear infinite",
        "screen-in": "screen-in 0.34s cubic-bezier(0.16,1,0.3,1) both",
        "iris-in": "iris-in 0.42s cubic-bezier(0.7,0,0.84,0) both",
        "fade-out": "fade-out 0.32s ease-out both",
        "fade-in": "fade-in 0.3s ease-out both",
        "count-in": "count-in 0.72s cubic-bezier(0.16,1,0.3,1) both",
        "go-in": "go-in 0.62s cubic-bezier(0.16,1,0.3,1) both",
        burst: "burst 0.6s cubic-bezier(0.16,1,0.3,1) both",
        "slide-up": "slide-up 0.5s cubic-bezier(0.16,1,0.3,1) both",
        "modal-in": "modal-in 0.28s cubic-bezier(0.16,1,0.3,1) both",
        stamp: "stamp 0.45s cubic-bezier(0.16,1,0.3,1) both",
        "prize-in": "prize-in 0.8s cubic-bezier(0.16,1,0.3,1) both",
        foil: "foil 3.2s ease-in-out infinite",
        "fall-loop": "fall-loop linear infinite",
        promo: "promo 3.6s ease-in-out both",
        "hold-ring": "hold-ring 1.2s linear both",
      },
    },
  },
  plugins: [],
} satisfies Config;
